### ISSUE TITLE
can't find the bend deformers

### ISSUE THREAD

**Issue by sanyi12** [cloudofoz/godot-deformablemesh#2]
I am using Godot 4.1.2 and there are no bend deformers. but what was the use of them anyway? is it better to use deformers than bones or shapekeys? thanks

**Comment by cloudofoz** [comment]
Hi @sanyi12 , thank you for trying out my addon. 

If you want to test bend deformers, please try downloading the github version (AssetLib actually has an older version of my addon, I was planning to do more testing before publishing it).

Generally speaking, bones and shapekeys should be preferred since they are natively supported by Godot Engine.

However, this add-on aims to enable the ability to create custom deformers that are fully manageable within the editor or via script without the use of a modelling app.
